"""Add last_notification_date to users

Revision ID: 27a74dbf6227
Revises: c2de98012337
Create Date: 2025-10-02 20:26:02.312115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a74dbf6227'
down_revision: Union[str, Sequence[str], None] = 'c2de98012337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_notification_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_notification_date')
    # ### end Alembic commands ###
