"""Set default for last_reset_date

Revision ID: 3fc647ee0a7c
Revises: 4b6c90828e15
Create Date: 2025-09-24 18:01:34.734003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fc647ee0a7c"
down_revision: Union[str, Sequence[str], None] = "4b6c90828e15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_reset_date",
        existing_type=sa.Date(),
        server_default=sa.text("CURRENT_DATE"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_reset_date",
        existing_type=sa.Date(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
