"""update pending_users table with command field

Revision ID: 9ce793824f08
Revises: 9491a29b186d
Create Date: 2025-08-29 12:50:04.332171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce793824f08'
down_revision: Union[str, Sequence[str], None] = '9491a29b186d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_users', sa.Column('command', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_users', 'command')
    # ### end Alembic commands ###
