"""Add last_seen and archived_at to jobs

Revision ID: a696048e20f1
Revises: e8d11914d5a4
Create Date: 2025-09-06 15:00:50.188839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a696048e20f1'
down_revision: Union[str, Sequence[str], None] = 'e8d11914d5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_filtered_jobs', 'datetime_added',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_filtered_jobs', 'datetime_added',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('jobs', 'archived_at')
    op.drop_column('jobs', 'last_seen')
    # ### end Alembic commands ###
