"""remove pending_user table

Revision ID: dd61c5ad9dae
Revises: 9ce793824f08
Create Date: 2025-08-29 14:12:37.375717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd61c5ad9dae'
down_revision: Union[str, Sequence[str], None] = '9ce793824f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_users_user_id'), table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('datetime_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('command', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_users_pkey'))
    )
    op.create_index(op.f('ix_pending_users_user_id'), 'pending_users', ['user_id'], unique=True)
    # ### end Alembic commands ###
