"""add_cascade_delete_to_user_filtered_jobs

Revision ID: de496a1454d0
Revises: 27c9b52195fc
Create Date: 2025-10-01 17:14:52.203210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de496a1454d0'
down_revision: Union[str, Sequence[str], None] = '27c9b52195fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_filtered_jobs_job_id_fkey'), 'user_filtered_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'user_filtered_jobs', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_filtered_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('user_filtered_jobs_job_id_fkey'), 'user_filtered_jobs', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
