"""Add daily limit fields to User

Revision ID: e7f2415e0f1d
Revises: a696048e20f1
Create Date: 2025-09-22 18:45:39.854413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7f2415e0f1d"
down_revision: Union[str, Sequence[str], None] = "a696048e20f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "refresh_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "vacancies_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "users", sa.Column("last_reset_date", sa.Date(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_reset_date")
    op.drop_column("users", "vacancies_count")
    op.drop_column("users", "refresh_count")
    # ### end Alembic commands ###
